image:
  repository: gcr.io/bisees-public/exepno-infrastructure
  tag: 1.0.0

ubbagent:
  image: gcr.io/cloud-marketplace-tools/metering/ubbagent:latest

reportingSecret: ""

serviceAccount:
  create: true
  name: ""

ingress:
  grafana_host: "grafana.example.com"
  jenkins_host: "jenkins.example.com"
  argocd_host: "argocd.example.com"
  airflow_host: "airflow.example.com"
  openmetadata_host: "openmetadata.example.com"
  kibana_host: "kibana.example.com"
  jira_host: "jira.example.com"
  confluence_host: "confluence.example.com"
  gitea_host: "git.example.com"
  kubeshark_host: "kubeshark.example.com"

monitoring:
  alertmanager:
    alertmanagerSpec:
      replicas: 3
      image:
        registry: gcr.io
        repository: bisees-public/exepno-infrastructure/alertmanager
        tag: 1.0.0
      storage:
        storageClassName: standard-rwo
        storage: 50Gi
  prometheusOperator:
    admissionWebhooks:
      patch:
        image:
          registry: gcr.io
          repository: bisees-public/exepno-infrastructure/patch
          tag: 1.0.0
    image:
      registry: gcr.io
      repository: bisees-public/exepno-infrastructure/prometheus-operator
      tag: 1.0.0
    prometheusConfigReloader:
      image:
        registry: gcr.io
        repository: bisees-public/exepno-infrastructure/prometheus-config-reloader
        tag: 1.0.0
  prometheus:
    prometheusSpec:
      replicas: 3
      image:
        registry: gcr.io
        repository: bisees-public/exepno-infrastructure/prometheus
        tag: 1.0.0
      storageSpec:
        storageClassName: standard-rwo
        storage: 50Gi
  grafana:
    adminPassword: ""
    replicas: 3
    image:
      repository: gcr.io/bisees-public/exepno-infrastructure/grafana
      tag: 1.0.0
    testFramework:
      image: gcr.io/bisees-public/exepno-infrastructure/bats
      tag: 1.0.0
    downloadDashboardsImage:
      repository: gcr.io/bisees-public/exepno-infrastructure/curl
      tag: 1.0.0
    initChownData:
      image:
        repository: gcr.io/bisees-public/exepno-infrastructure/busybox
        tag: 1.0.0
    sidecar:
      image:
        repository: gcr.io/bisees-public/exepno-infrastructure/k8s-sidecar
        tag: 1.0.0
    persistence:
      storageClassName: standard-rwo
      size: 10Gi
  prometheusNodeExporter:
    image:
      repository: gcr.io/bisees-public/exepno-infrastructure/node-exporter
      tag: 1.0.0
  kubeStateMetrics:
    replicas: 3
    image:
      repository: gcr.io/bisees-public/exepno-infrastructure/kube-state-metrics
      tag: 1.0.0

postgresql:
  replicas: 3
  global:
    postgresql:
      auth:
        password: ""
        postgresPassword: ""
        username: exepno
        database: exepno
      persistence:
        storageClass: standard-rwo
        size: 50Gi

jenkins:
  controller:
    adminPassword: ""
    image: gcr.io/bisees-public/exepno-infrastructure/jenkins
    tag: 1.0.0
    sidecars:
      configAutoReload:
        image: gcr.io/bisees-public/exepno-infrastructure/jenkins-k8s-sidecar:1.0.0
  agent:
    image: gcr.io/bisees-public/exepno-infrastructure/inbound-agent
    tag: 1.0.0
  helmtest:
    bats:
      image: gcr.io/bisees-public/exepno-infrastructure/jenkins-bats
      tag: 1.0.0
  serviceAccountAgent:
    name: jenkins-workers
  persistence:
    storageClass: standard-rwo
    size: 10Gi

argocd:
  global:
    image:
      repository: gcr.io/bisees-public/exepno-infrastructure/argocd
      tag: 1.0.0
  redis:
    exporter:
      image: gcr.io/bisees-public/exepno-infrastructure/redis-exporter
      tag: 1.0.0
    persistentVolume:
      storageClass: "standard-rwo"
      size: 10Gi
  server:
    replicas: 3
    extensions:
      image:
        repository: gcr.io/bisees-public/exepno-infrastructure/argocd-extensions
        tag: 1.0.0
  controller:
    replicas: 3
  repoServer:
    replicas: 3
  applicationSet:
    replicas: 3

nfs:
  replicaCount: 3
  image:
    repository: gcr.io/bisees-public/exepno-infrastructure/nfs-provisioner
    tag: 1.0.0
  persistence:
    storageClass: "standard-rwo"
    size: 50Gi

openmetadataDependencies:
  secrets:
    openmetadataAirflowPassword: ""
    saEmail: "airflow-sa@mygcp-project.iam.gserviceaccount.com"
    # github_username: ""
    # github_token: ""
  airflow:
    airflow:
      crawlOutputBucket: "airflow-dags"
      logsOutputBucket: "airflow-logs"
      adminEmail: "airflow@test.com"
      adminFirstName: "Airflow"
      adminLastName: "Admin"
    dags:
      persistence:
        size: 5Gi
      gitSync:
        image:
          repository: gcr.io/bisees-public/exepno-infrastructure/git-sync
          tag: 1.0.0
    pgbouncer:
      image:
        repository: gcr.io/bisees-public/exepno-infrastructure/pgbouncer
        tag: 1.0.0
    scheduler:
      replicas: 3
    web:
      replicas: 3
    triggerer:
      replicas: 3
  mysql:
    replicaCount: 3
    image:
      registry: gcr.io
      repository: bisees-public/exepno-infrastructure/om-mysql
      tag: 1.0.0
    auth:
      rootPassword: ""
    persistence:
      storageClass: standard-rwo
      size: 50Gi
  elasticsearch:
    replicas: 1
    persistence:
      storageClassName: standard-rwo
      storage: 30Gi

openmetadata:
  image:
    repository: gcr.io/bisees-public/exepno-infrastructure/openmetadata
    tag: 1.0.0
  password: ""
  replicaCount: 3

eck:
  operator:
    replicaCount: 1
    image:
      repository: gcr.io/bisees-public/exepno-infrastructure/eck-operator
      tag: 1.0.0
  elasticsearch:
    image: gcr.io/bisees-public/exepno-infrastructure/elasticsearch:1.0.0
    count: 3
    persistence:
      storageClassName: standard-rwo
      storage: 50Gi
  kibana:
    image: gcr.io/bisees-public/exepno-infrastructure/kibana:1.0.0
    count: 3
  metricbeat:
    image: gcr.io/bisees-public/exepno-infrastructure/metricbeat:1.0.0
  filebeat:
    image: gcr.io/bisees-public/exepno-infrastructure/filebeat:1.0.0

jira:
  replicaCount: 3
  global:
    postgresql:
      replicas: 3
      auth:
        password: ""
        postgresPassword: ""
      image:
        registry: gcr.io
        repository: bisees-public/exepno-infrastructure/postgresql
        tag: 1.0.0
      volumePermissions:
        image:
          registry: gcr.io
          repository: bisees-public/exepno-infrastructure/bitnami-shell
          tag: 1.0.0
      metrics:
        image:
          registry: gcr.io
          repository: bisees-public/exepno-infrastructure/postgres-exporter
          tag: 1.0.0
      persistence:
        storageClass: standard-rwo
        size: 10Gi
  nfsPermissionFixer:
    imageRepo: gcr.io/bisees-public/exepno-infrastructure/alpine
    imageTag: 1.0.0
  persistence:
    storageClassName: standard-rwo
    storage: 10Gi
    sharedStorage: 10Gi

confluence:
  replicaCount: 3
  global:
    postgresql:
      replicas: 3
      auth:
        password: ""
        postgresPassword: ""
      image:
        registry: gcr.io
        repository: bisees-public/exepno-infrastructure/postgresql
        tag: 1.0.0
      volumePermissions:
        image:
          registry: gcr.io
          repository: bisees-public/exepno-infrastructure/bitnami-shell
          tag: 1.0.0
      metrics:
        image:
          registry: gcr.io
          repository: bisees-public/exepno-infrastructure/postgres-exporter
          tag: 1.0.0
      persistence:
        storageClass: standard-rwo
        size: 10Gi
  nfsPermissionFixer:
    imageRepo: gcr.io/bisees-public/exepno-infrastructure/alpine
    imageTag: 1.0.0
  persistence:
    storageClassName: standard-rwo
    storage: 10Gi
    sharedStorage: 10Gi
    synchronyStorage: 10Gi
  synchrony:
    replicaCount: 3

gitea:
  replicaCount: 3
  image:
    registry: gcr.io
    repository: bisees-public/exepno-infrastructure/gitea
    tag: 1.0.0
  test:
    image:
      name: gcr.io/bisees-public/exepno-infrastructure/busybox
      tag: 1.0.0
  config:
    APP_NAME: "Gitea: Git with a cup of tea"
  admin:
    username: "admin"
    password: ""
    email: "gitea@test.com"
  postgresql:
    replicas: 3
    password: ""
    image:
      registry: gcr.io
      repository: bisees-public/exepno-infrastructure/postgresql
      tag: 1.0.0
    persistence:
      storageClass: standard-rwo
      size: 10Gi
  memcached:
    replicas: 3
    image:
      registry: gcr.io
      repository: bisees-public/exepno-infrastructure/memcached
      tag: 1.0.0
  persistence:
    storageClass: standard-rwo
    size: 10Gi

kubeshark:
  docker:
    registry: gcr.io/bisees-public/exepno-infrastructure
    tag: 1.0.0
  approveddomains: "gmail.com,outlook.com"
  storagelimit: 1Gi
  license: ""