{{- $reportingSecret := required "Please provide Reporting Secret using --set reportingSecret=<secret_name>" .Values.reportingSecret -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exepno-infrastructure.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "exepno-infrastructure.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "exepno-infrastructure.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "exepno-infrastructure.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "exepno-infrastructure.serviceAccountName" . }}
      terminationGracePeriodSeconds: 300
      volumes:
        - name: values
          secret:
            secretName: {{ include "exepno-infrastructure.fullname" . }}
        - name: report
          secret:
            secretName: {{ $reportingSecret }}
        - name: ubbagent-config
          configMap:
            name: {{ include "exepno-infrastructure.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FULL_NAME
              value: {{ include "exepno-infrastructure.fullname" . }}
            - name: SA_NAME
              value: {{ include "exepno-infrastructure.serviceAccountName" . }}
          volumeMounts:
            - mountPath: /values
              name: values
            - mountPath: /billing
              name: report
          startupProbe:
            exec:
              command:
                - bash
                - -c
                - cat /apps/finished
            initialDelaySeconds: 600
            failureThreshold: 30
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - cat /apps/finished
            initialDelaySeconds: 600
            failureThreshold: 10
            periodSeconds: 30
        - name: ubbagent
          image: {{ .Values.ubbagent.image }}
          env:
          - name: AGENT_CONFIG_FILE
            value: "/etc/ubbagent/config.yaml"
          - name: AGENT_LOCAL_PORT
            value: "4567"
          - name: AGENT_ENCODED_KEY
            valueFrom:
              secretKeyRef:
                name: {{ $reportingSecret }}
                key: reporting-key
          - name: AGENT_CONSUMER_ID
            valueFrom:
              secretKeyRef:
                name: {{ $reportingSecret }}
                key: consumer-id
          volumeMounts:
          - name: ubbagent-config
            mountPath: /etc/ubbagent