{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "exepno-infrastructure.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "exepno-infrastructure.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
